# src/recommendation.py
"""Recommendation engine for Lucy AI‑DJ.

Provides a simple rule‑based track selector that reads the music library
index stored in ``data/library_index.db`` (generated by ``library_indexer``).
The public function :func:`get_next_recommendation` is used by Liquidsoap
(and later by the DJ agent) to obtain the next track to play.

The implementation is deliberately lightweight: it avoids playing the same
track repeatedly within a short window and falls back to a random choice when
no eligible tracks remain.
"""

import random
import sqlite3
from pathlib import Path
from typing import Dict, List, Tuple

# Resolve the path to the SQLite database – same location as library_indexer
DB_PATH = Path(__file__).resolve().parents[2] / "data" / "library_index.db"


def _fetch_all_tracks() -> List[Tuple[int, str, str, str, str, int, str]]:
    """Return a list of all tracks in the database.

    Each entry is a tuple matching the columns defined in ``library_indexer``:
    ``(id, path, title, artist, album, duration, genre)``.
    """
    conn = sqlite3.connect(DB_PATH)
    cur = conn.cursor()
    cur.execute(
        "SELECT id, path, title, artist, album, duration, genre FROM tracks"
    )
    rows = cur.fetchall()
    conn.close()
    return rows


def _track_to_dict(row: Tuple[int, str, str, str, str, int, str]) -> Dict:
    """Convert a raw DB row into a serialisable ``dict``.

    ``duration`` may be ``None`` – we keep the value as‑is for downstream
    consumers.
    """
    (track_id, path, title, artist, album, duration, genre) = row
    return {
        "id": track_id,
        "path": path,
        "title": title,
        "artist": artist,
        "album": album,
        "duration": duration,
        "genre": genre,
    }


def get_next_recommendation(previous_tracks: List[int]) -> Dict:
    """Select the next track to play.

    Parameters
    ----------
    previous_tracks:
        A list of track ``id`` values that have been recently played. The
        engine attempts to avoid returning any of these IDs.

    Returns
    -------
    dict
        A dictionary representing the chosen track – the same shape as the
        output of :func:`_track_to_dict`.

    Notes
    -----
    * If *all* tracks are in ``previous_tracks`` the history is cleared and a
      random track from the full library is returned.
    * The selection strategy is currently random; more sophisticated scoring
      (e.g., based on genre rotation, DJ‑agent confidence, or user feedback)
      can be added later without changing the public interface.
    """
    all_tracks = _fetch_all_tracks()
    if not all_tracks:
        raise RuntimeError("Music library is empty – ensure library_indexer has run.")

    # Filter out recently played tracks
    eligible = [row for row in all_tracks if row[0] not in previous_tracks]
    if not eligible:
        # All tracks have been recently played – reset history
        eligible = all_tracks

    chosen_row = random.choice(eligible)
    return _track_to_dict(chosen_row)


if __name__ == "__main__":
    # Simple manual test – prints a random track JSON
    import json
    print(json.dumps(get_next_recommendation(previous_tracks=[]), indent=2))
